### ISSUE TITLE
git-stack picks up a wrong GPG key for signing commits

### ISSUE THREAD

**Issue by bemyak** [gitext-rs/git-stack#286]
### Please complete the following tasks

- [X] I have searched the [discussions](https://github.com/gitext-rs/git-stack/discussions)
- [X] I have searched the existing issues

### Description

Git-stack picks up the first GPG key to sign commits.

I have a set of GPG keys set up in the following order (`gpg --list-secret-keys --keyid-format LONG`):
1. `old-work@email.com` (an email left from the previous job, not mentioned in any git configs or env vars)
2. `private@email.com`
3. `work@email.com`

Whenever I run `git sync`, it always tries to sign commits with the first key from the list (i.e. `old-work@email.com`).

### Version

0.10.10

### Steps to reproduce

1. Run `gpg --full-generate-key` multiple times to create a couple of GPG keys. To make testing easier, I recommend setting different passphrases for them.
   1. `email1@email.com`
   2. `email2@email.com`
   3. `email3@email.com`
2. Set git email to `email2@email.com`: `git config --global user.email "email2@email.com"`
3. Force git to sign all commits: `git config --global commit.gpgSign true`
4. Set env variables to `email3@email.com`:
   1. `export GIT_AUTHOR_EMAIL=email3@email.com`
   2. `export GIT_COMMITTER_EMAIL=email3@email.com`
5. Run `git sync` in any repo that will require rebasing and resigning commits

### Actual Behaviour

Git-sync signs commits with `email1@email.com` key

### Expected Behaviour

Git-sync should pick up a key in the following priority:
* `GIT_COMMITTER_EMAIL`
* `~/.config/git/config`
* `~/.gitconfig`

**Comment by epage** [comment]
**Could you confirm if the committer (not author) for rewritten commits is respecting `GIT_COMMITTER_NAME` / `GIT_COMMITTER_EMAIL` or not?**  That'll confirm where the bug is.

## Investigation notes

[We do a fallback of](https://github.com/gitext-rs/git2-ext/blob/main/src/ops.rs#L310)
- `user.signingkey`
- repo signature as reported by libgit2
  - [libgit2 seems to exclusively read user.name/user.email](https://github.com/libgit2/libgit2/blob/1327dbcf2a4273a8ba6fd978db5f0882530af94d/src/libgit2/signature.c#L188)

[git's fallback](https://github.com/git/git/blob/master/gpg-interface.c#L899) is
- `configured_signing_key`
  - which comes from [`set_signing_key`](https://github.com/git/git/blob/master/gpg-interface.c#L696)
    - which comes from [`user.signingkey`](https://github.com/git/git/blob/master/gpg-interface.c#L709)
- `get_default_key`
  - which is [skipped for gpg](https://github.com/git/git/blob/master/gpg-interface.c#L80)
- `git_committer_info(IDENT_STRICT | IDENT_NO_DATE);`
  - I made the best guess that this would align with the repo's signature but that was harder to follow
  - Looks like it [reads the env for GIT_COMMITTER_NAME / GIT_COMMITER_EMAIL](https://github.com/git/git/blob/36f8e7ed7d72d2ac73743c3c2226cceb29b32156/ident.c#L572) first
  - It then [fallsback](https://github.com/git/git/blob/36f8e7ed7d72d2ac73743c3c2226cceb29b32156/ident.c#L462) to [author.name / author.email](https://github.com/git/git/blob/36f8e7ed7d72d2ac73743c3c2226cceb29b32156/ident.c#L606)

From looking at this, it **seems** like git2 isn't reading GIT_COMMITTER_NAME  / GIT_COMMITER_EMAIL but should be reading the configs in the correct order.  The way to confirm this is for any other place we read the repo signature and see if its wrong.  We generate a new signature for the committer when we rewrite history, using the repo's signature.

**Comment by bemyak** [comment]
Given the setup I described in the reproduction steps, the final result of running `git sync` is (as shown by `git log --format=full --show-signature`):
```
signature: email1@email.com
Author: email3@email.com
Commit: email2@email.com
```
So, it looks like the author field respects `GIT_AUTHOR_EMAIL` and `GIT_AUTHOR_NAME`

The committer is taken from git config file (`~/.gitconfig`) and the env vars `GIT_COMMITTER_EMAIL` and `GIT_COMMITTER_NAME` **are ignored**

And the signature is the first signature from the list, this email isn't used anywhere in git configs.

**Comment by epage** [comment]
> The committer is taken from the git config file (~/.gitconfig) and the env vars GIT_COMMITTER_EMAIL and GIT_COMMITTER_NAME are ignored

Can you open a bug about this?

> And the signature is the first signature from the list, this email isn't used anywhere in git configs.

The fact that the signature and committer are using different emails is bizarre as they **should** be coming from the same source.

Everytime I've used gpg, it has been an abysmal failure to the point I don't touch it.  I wrote all of this code blind, just reading git's source code.  Would you be able to help out in debugging this?  

- https://github.com/gitext-rs/git2-ext/blob/main/src/ops.rs#L310 is where we read the email
- https://github.com/gitext-rs/git2-ext/blob/main/src/ops.rs#L395 is where we pass it in to sign with

To use a local copy of `git2-ext` with `git-stack`, you can add the following to `Cargo.toml`:
```toml
[patch.crates-io]
git2-ext = { path = "<put path in here>" }
```

**Comment by bemyak** [comment]
I came up with a partial fix in the PR linked above. Now the key matches the committer, at least.

However, the committer field still doesn't respect the env variables. I skimmed through the code and found only one suspicion line [here](https://github.com/gitext-rs/git-stack/blob/main/src/git/repo.rs#L227), where committer is set to an author, but it is an irrelevant part of the code.

In which project can the issue be?

**Comment by epage** [comment]
> However, the committer field still doesn't respect the env variables. 

The call that is a problem is `repo.signature()` as [libgit2 is returning the bad information](https://github.com/libgit2/libgit2/blob/1327dbcf2a4273a8ba6fd978db5f0882530af94d/src/libgit2/signature.c#L188).  The way I would fix this is add a new `signature` function to git2-ext that checks the env variables and then falls back to `repo.signature()`.  It'll need to mimic what [git does when only one or the other env variable is set](https://github.com/git/git/blob/36f8e7ed7d72d2ac73743c3c2226cceb29b32156/ident.c#L462).  It should also read the env using `std::env::var_os` as `std::env_var` can panic.

**Comment by bemyak** [comment]
BTW, have you considered switching to [gitoxide](https://github.com/Byron/gitoxide)? This case seems to be handled correctly there. (Not asking to rewrite the entire set of gitext tools to gitoxide, just wondering :slightly_smiling_face: )

**Comment by bemyak** [comment]
> `std::env_var` can panic

According to [docs](https://doc.rust-lang.org/std/env/fn.var.html#errors), it should not. It returns an error if the var contains an invalid Unicode. So I'll use it as we are not handling non-Unicode symbols elsewhere.

**Comment by epage** [comment]
Good call. I got it mixed up with `std::env::args` (love that inconsistency)

**Comment by bemyak** [comment]
I did one more fix: https://github.com/gitext-rs/git2-ext/pull/28

Now the signature is correct, but the committer is not :)

**Comment by bemyak** [comment]
I can't find a section in the code where commits are created.

[Here](https://github.com/gitext-rs/git-stack/blob/main/src/git/repo.rs#L227) only a `name()` is used, so I can't figure out where does email come from, and why is it different from the original commit.
